spring:
  liquibase:
    change-log: classpath:db/changelog/changeLog.master.xml
    default-schema: public
  application:
    name: IntegracaoConta-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/contaAsaas
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95alect
      ddl-auto: validate
    open-in-view: true
    show-sql: true

asaas:
  dominio: 'https://sandbox.asaas.com/api/v3/customers'
  apiKey: "$"

server:
  port: 8080